"""Shared error model with stable, documented error codes.

Design ref: design.md §8.1 (Deterministic Corner Cases), implementation-plan.md Phase 1 task 4.
Per CONVENTIONS.md, a code is never reused for a different meaning once shipped.
HTTP status mapping is consumed only by api/errors.py — this module has no web framework
dependency so it stays usable from jaasctl.
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    INVALID_ID_FORMAT = "INVALID_ID_FORMAT"
    INVALID_VERSION_FORMAT = "INVALID_VERSION_FORMAT"
    INVALID_RUNTIME_FORMAT = "INVALID_RUNTIME_FORMAT"
    INVALID_DEPENDENCY_CONSTRAINT = "INVALID_DEPENDENCY_CONSTRAINT"
    CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY"
    MISSING_DEPENDENCY = "MISSING_DEPENDENCY"
    DUPLICATE_PUBLISH = "DUPLICATE_PUBLISH"
    CORRUPT_PAYLOAD = "CORRUPT_PAYLOAD"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    RUNTIME_MISMATCH = "RUNTIME_MISMATCH"
    UNAUTHORIZED = "UNAUTHORIZED"
    SKILL_NOT_FOUND = "SKILL_NOT_FOUND"
    VERSION_NOT_FOUND = "VERSION_NOT_FOUND"
    INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    INVALID_DEV_LOGIN = "INVALID_DEV_LOGIN"
    DEV_LOGIN_NOT_CONFIGURED = "DEV_LOGIN_NOT_CONFIGURED"
    TENANT_NOT_FOUND = "TENANT_NOT_FOUND"
    NOT_TENANT_MEMBER = "NOT_TENANT_MEMBER"
    DRAFT_NOT_FOUND = "DRAFT_NOT_FOUND"
    INVALID_FILE_PATH = "INVALID_FILE_PATH"
    MISSING_REQUIRED_FILE = "MISSING_REQUIRED_FILE"
    PAT_NOT_FOUND = "PAT_NOT_FOUND"
    SKILL_FILE_NOT_FOUND = "SKILL_FILE_NOT_FOUND"
    GUARDRAIL_VIOLATION = "GUARDRAIL_VIOLATION"
    GUARDRAILS_SERVICE_UNAVAILABLE = "GUARDRAILS_SERVICE_UNAVAILABLE"
    CUSTOM_GUARDRAIL_NOT_FOUND = "CUSTOM_GUARDRAIL_NOT_FOUND"
    GUARDRAIL_RULE_LIMIT_EXCEEDED = "GUARDRAIL_RULE_LIMIT_EXCEEDED"
    INVALID_CUSTOM_GUARDRAIL = "INVALID_CUSTOM_GUARDRAIL"
    CUSTOM_GUARDRAIL_DRAFT_NOT_FOUND = "CUSTOM_GUARDRAIL_DRAFT_NOT_FOUND"
    REPO_LINK_NOT_FOUND = "REPO_LINK_NOT_FOUND"
    REPO_LINK_REQUIRED = "REPO_LINK_REQUIRED"
    INVALID_CI_CREDENTIAL = "INVALID_CI_CREDENTIAL"
    RELEASE_VERSION_MISMATCH = "RELEASE_VERSION_MISMATCH"
    RELEASE_LINE_NOT_ALLOWED = "RELEASE_LINE_NOT_ALLOWED"
    GITHUB_NOT_CONNECTED = "GITHUB_NOT_CONNECTED"
    GITHUB_OAUTH_NOT_CONFIGURED = "GITHUB_OAUTH_NOT_CONFIGURED"
    INVALID_GITHUB_STATE = "INVALID_GITHUB_STATE"
    GITHUB_API_ERROR = "GITHUB_API_ERROR"
    DRAFT_GIT_SYNC_FAILED = "DRAFT_GIT_SYNC_FAILED"
    DRAFT_GIT_BRANCH_EXISTS = "DRAFT_GIT_BRANCH_EXISTS"
    DRAFT_GIT_MERGE_CONFLICT = "DRAFT_GIT_MERGE_CONFLICT"
    DRAFT_GIT_EMPTY_REPO = "DRAFT_GIT_EMPTY_REPO"
    DRAFT_GIT_NOT_CONNECTED = "DRAFT_GIT_NOT_CONNECTED"
    DRAFT_GIT_ALREADY_HAS_DIRECTORY = "DRAFT_GIT_ALREADY_HAS_DIRECTORY"
    SIGSTORE_SIGNATURE_REQUIRED = "SIGSTORE_SIGNATURE_REQUIRED"


HTTP_STATUS_BY_CODE: dict[ErrorCode, int] = {
    ErrorCode.SCHEMA_VALIDATION_FAILED: 400,
    ErrorCode.INVALID_ID_FORMAT: 400,
    ErrorCode.INVALID_VERSION_FORMAT: 400,
    ErrorCode.INVALID_RUNTIME_FORMAT: 400,
    ErrorCode.INVALID_DEPENDENCY_CONSTRAINT: 400,
    ErrorCode.CIRCULAR_DEPENDENCY: 400,
    ErrorCode.MISSING_DEPENDENCY: 400,
    ErrorCode.DUPLICATE_PUBLISH: 409,
    ErrorCode.CORRUPT_PAYLOAD: 400,
    ErrorCode.INVALID_SIGNATURE: 400,
    ErrorCode.RUNTIME_MISMATCH: 404,
    ErrorCode.UNAUTHORIZED: 403,
    ErrorCode.SKILL_NOT_FOUND: 404,
    ErrorCode.VERSION_NOT_FOUND: 404,
    ErrorCode.INVALID_GOOGLE_TOKEN: 401,
    ErrorCode.INVALID_REFRESH_TOKEN: 401,
    ErrorCode.INVALID_DEV_LOGIN: 401,
    ErrorCode.DEV_LOGIN_NOT_CONFIGURED: 501,
    ErrorCode.TENANT_NOT_FOUND: 404,
    ErrorCode.NOT_TENANT_MEMBER: 403,
    ErrorCode.DRAFT_NOT_FOUND: 404,
    ErrorCode.INVALID_FILE_PATH: 400,
    ErrorCode.MISSING_REQUIRED_FILE: 400,
    ErrorCode.PAT_NOT_FOUND: 404,
    ErrorCode.SKILL_FILE_NOT_FOUND: 404,
    ErrorCode.GUARDRAIL_VIOLATION: 400,
    ErrorCode.GUARDRAILS_SERVICE_UNAVAILABLE: 503,
    ErrorCode.CUSTOM_GUARDRAIL_NOT_FOUND: 404,
    ErrorCode.GUARDRAIL_RULE_LIMIT_EXCEEDED: 400,
    ErrorCode.CUSTOM_GUARDRAIL_DRAFT_NOT_FOUND: 404,
    ErrorCode.INVALID_CUSTOM_GUARDRAIL: 400,
    ErrorCode.REPO_LINK_NOT_FOUND: 404,
    ErrorCode.REPO_LINK_REQUIRED: 403,
    ErrorCode.INVALID_CI_CREDENTIAL: 401,
    ErrorCode.RELEASE_VERSION_MISMATCH: 400,
    ErrorCode.RELEASE_LINE_NOT_ALLOWED: 403,
    ErrorCode.GITHUB_NOT_CONNECTED: 404,
    ErrorCode.GITHUB_OAUTH_NOT_CONFIGURED: 501,
    ErrorCode.INVALID_GITHUB_STATE: 400,
    ErrorCode.GITHUB_API_ERROR: 502,
    ErrorCode.DRAFT_GIT_SYNC_FAILED: 502,
    ErrorCode.DRAFT_GIT_BRANCH_EXISTS: 409,
    ErrorCode.DRAFT_GIT_MERGE_CONFLICT: 409,
    ErrorCode.DRAFT_GIT_EMPTY_REPO: 409,
    ErrorCode.DRAFT_GIT_NOT_CONNECTED: 400,
    ErrorCode.DRAFT_GIT_ALREADY_HAS_DIRECTORY: 409,
    ErrorCode.SIGSTORE_SIGNATURE_REQUIRED: 400,
}


class JaasError(Exception):
    """Base exception for every deterministic registry rejection."""

    def __init__(self, code: ErrorCode, message: str, *, details: dict | None = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.details = details or {}

    def to_dict(self) -> dict:
        return {"code": self.code.value, "message": self.message, "details": self.details}
